cards:
  - index: 11
    name: Secure objective 1
    category: Capture and control *
    fluff: A vital objective has been identified in your vicinity. You are ordered to hold it at any cost.
    text: Score 1 victory point if you control objective marker 1 at the end of your turn.
    points:
      - 1
  - index: 12
    name: Secure objective 2
    category: Capture and control *
    fluff: A vital objective has been identified in your vicinity. You are ordered to hold it at any cost.
    text: Score 1 victory point if you control objective marker 2 at the end of your turn.
    points:
      - 1
  - index: 13
    name: Secure objective 3
    category: Capture and control *
    fluff: A vital objective has been identified in your vicinity. You are ordered to hold it at any cost.
    text: Score 1 victory point if you control objective marker 3 at the end of your turn.
    points:
      - 1
  - index: 14
    name: Secure objective 4
    category: Capture and control *
    fluff: A vital objective has been identified in your vicinity. You are ordered to hold it at any cost.
    text: Score 1 victory point if you control objective marker 4 at the end of your turn.
    points:
      - 1
  - index: 15
    name: Secure objective 5
    category: Capture and control *
    fluff: A vital objective has been identified in your vicinity. You are ordered to hold it at any cost.
    text: Score 1 victory point if you control objective marker 5 at the end of your turn.
    points:
      - 1
  - index: 16
    name: Secure objective 6
    category: Capture and control *
    fluff: A vital objective has been identified in your vicinity. You are ordered to hold it at any cost.
    text: Score 1 victory point if you control objective marker 6 at the end of your turn.
    points:
      - 1
  - index: 21
    name: Secure objective 1
    category: Take and hold
    fluff: A vital objective has been identified in your vicinity. You are ordered to hold it at any cost.
    text: Score 1 victory point if you control objective marker 1 at the end of your turn.
    points:
      - 1
  - index: 22
    name: Secure objective 2
    category: Take and hold
    fluff: A vital objective has been identified in your vicinity. You are ordered to hold it at any cost.
    text: Score 1 victory point if you control objective marker 2 at the end of your turn.
    points:
      - 1
  - index: 23
    name: Secure objective 3
    category: Take and hold
    fluff: A vital objective has been identified in your vicinity. You are ordered to hold it at any cost.
    text: Score 1 victory point if you control objective marker 3 at the end of your turn.
    points:
      - 1
  - index: 24
    name: Secure objective 4
    category: Take and hold
    fluff: A vital objective has been identified in your vicinity. You are ordered to hold it at any cost.
    text: Score 1 victory point if you control objective marker 4 at the end of your turn.
    points:
      - 1
  - index: 25
    name: Secure objective 5
    category: Take and hold
    fluff: A vital objective has been identified in your vicinity. You are ordered to hold it at any cost.
    text: Score 1 victory point if you control objective marker 5 at the end of your turn.
    points:
      - 1
  - index: 26
    name: Secure objective 6
    category: Take and hold
    fluff: A vital objective has been identified in your vicinity. You are ordered to hold it at any cost.
    text: Score 1 victory point if you control objective marker 6 at the end of your turn.
    points:
      - 1
  - index: 31
    name: Defend objective 1
    category: Storm and defend
    fluff: You are charged with the defence of a key objective. It must not be permitted to fall into enemy hands.
    text: Score 2 victory points if you control objective marker 1 at the end of two consecutive turns.
    points:
      - 2
  - index: 32
    name: Defend objective 2
    category: Storm and defend
    fluff: You are charged with the defence of a key objective. It must not be permitted to fall into enemy hands.
    text: Score 2 victory points if you control objective marker 2 at the end of two consecutive turns.
    points:
      - 2
  - index: 33
    name: Defend objective 3
    category: Storm and defend
    fluff: You are charged with the defence of a key objective. It must not be permitted to fall into enemy hands.
    text: Score 2 victory points if you control objective marker 3 at the end of two consecutive turns.
    points:
      - 2
  - index: 34
    name: Defend objective 4
    category: Storm and defend
    fluff: You are charged with the defence of a key objective. It must not be permitted to fall into enemy hands.
    text: Score 2 victory points if you control objective marker 4 at the end of two consecutive turns.
    points:
      - 2
  - index: 35
    name: Defend objective 5
    category: Storm and defend
    fluff: You are charged with the defence of a key objective. It must not be permitted to fall into enemy hands.
    text: Score 2 victory points if you control objective marker 5 at the end of two consecutive turns.
    points:
      - 2
  - index: 36
    name: Defend objective 6
    category: Storm and defend
    fluff: You are charged with the defence of a key objective. It must not be permitted to fall into enemy hands.
    text: Score 2 victory points if you control objective marker 6 at the end of two consecutive turns.
    points:
      - 2
  - index: 41
    name: Advance
    category: Seize ground
    fluff: You must advance swiftly into no man’s land to prevent your opponent seizing the battlefield.
    text: Score 1 victory point if no unit from your army is within your deployment zone at the end of your turn.
    points:
      - 1
  - index: 42
    name: Behind enemy lines
    category: Seize ground
    fluff: Break through the foe’s army and cut off their lines of escape.
    text: Score 1 victory point if you have at least one unit completely within the enemy’s deployment zone at the end of your turn. If you have at least three units within your opponent’s deployment zone at the end of your turn, score D3 victory points instead.
    points:
      - 1
      - d3
  - index: 43
    name: Hold the line
    category: Seize ground
    fluff: It is critical that no foe breaks through your defences. Maintain a strong rearguard to protect your supply lines.
    text: Score 1 victory point if you have at least three units completely within your deployment zone, and your opponent has no models within your deployment zone, at the end of your turn. This objective cannot be achieved on your first turn.
    points:
      - 1
  - index: 44
    name: Mission critical objective
    category: Seize ground
    fluff: This area is of extreme importance. You are to lead an immediate all-out assault to capture it.
    text: When this Tactical Objective is generated, roll a D6. Score 1 victory point if you control the corresponding objective marker. If the corresponding objective marker was controlled by your opponent at the start of your turn and you control it at the end of your turn, score D3 victory points instead.
    points:
      - 1
      - d3
  - index: 45
    name: Supremacy
    category: Seize ground
    fluff: The battleground is won one yard at a time. Continue to establish a strong military presence in the area.
    text: Score D3 victory points if you control any three objective markers at the end of your turn.
    points:
      - d3
  - index: 46
    name: Domination
    category: Seize ground
    fluff: Dominate the field of battle. Storm every site of tactical import and leave the foe with no place to hide.
    text: Score D3+3 victory points if you control every objective marker on the battlefield at the end of your turn.
    points:
      - d3+3
  - index: 51
    name: Overwhelming firepower
    category: Purge
    fluff: A show of strength is required. Scour the enemy from the face of the battlefield with the use of extreme firepower.
    text: Score 1 victory point if an enemy unit was destroyed during the Shooting phase of your turn. If 3 or more enemy units were destroyed during the Shooting phase of your turn, score D3 victory points instead.
    points:
      - 1
      - d3
  - index: 52
    name: Blood and guts
    category: Purge
    fluff: Close with the foe and engage them in hand-to-hand combat. Show them no quarter, no mercy.
    text: Score 1 victory point if an enemy unit was destroyed during the Fight phase of this turn. If 3 or more enemy units were destroyed during the Fight phase of this turn, score D3 victory points instead.
    points:
      - 1
      - d3
  - index: 53
    name: No prisoners
    category: Purge
    fluff: Exterminate your enemy, show them no mercy.
    text: Score 1 victory point if an enemy unit was destroyed during your turn. If between 3 and 5 enemy units were destroyed during your turn, score D3 victory points instead. If 6 or more enemy units were destroyed during your turn, score D3+3 victory points instead.
    points:
      - 1
      - d3
      - d3+3
  - index: 54
    name: Area denial
    category: Purge
    fluff: It is critical that this area is dominated. No enemy vanguard or guerilla units can be allowed to disrupt our plans.
    text: Score 1 victory point if there are no enemy models within 6" of the centre of the battlefield at the end of your turn. If there are no enemy models within 12" of the centre of the battlefield at the end of your turn, score D3 victory points instead.
    points:
      - d3
  - index: 55
    name: Psychological warfare
    category: Purge
    fluff: Break the enemy’s morale, make your foes tremble before you.
    text: Score 1 victory point if your opponent failed a Morale test during this turn. If your opponent failed 3 or more Morale tests, score D3 victory points instead.
    points:
      - 1
      - d3
  - index: 56
    name: Master the warp
    category: Purge
    fluff: Desperate times call for desperate measures – harness the power of the warp to defeat your foes.
    text: Score 1 victory point if you manifested or denied a psychic power during this turn. If you manifested or denied 3 or more psychic powers, score D3 victory points instead.
    points:
      - 1
      - d3
  - index: 61
    name: Kingslayer
    category: Priority order
    fluff: The enemy commander is a powerful and effective leader and should be slain as quickly as possible.
    text: Score D3 victory points if your opponent’s Warlord has been destroyed during this or any previous turn.
    points:
      - d3
  - index: 62
    name: Witch hunter
    category: Priority order
    fluff: The presence of enemy psykers can no longer be tolerated. Eliminate them with extreme prejudice.
    text: Score 1 victory point if at least one enemy PSYKER was destroyed during this turn.
    points:
      - 1
  - index: 63
    name: Scour the skies
    category: Priority order
    fluff: It is vital to maintain air superiority.
    text: Score 1 victory point if at least one enemy unit that can FLY was destroyed during this turn.
    points:
      - 1
  - index: 64
    name: Assassinate
    category: Priority order
    fluff: The enemy looks to their champions for courage. Identify and assassinate them.
    text: Score 1 victory point if at least one enemy CHARACTER was destroyed during this turn. If 3 or more enemy CHARACTERS were destroyed during this turn, score D3 victory points instead.
    points:
      - 1
      - d3
  - index: 65
    name: Big game hunter
    category: Priority order
    fluff: The larger the foe, the greater the glory…
    text: Score 1 victory point if at least one enemy unit with a Wounds characteristic of 10 or more was destroyed during this turn. If at least one enemy unit with a Wounds characteristic of 20 or more was destroyed this turn, score D3 victory points instead.
    points:
      - 1
      - d3
  - index: 66
    name: Priority orders received
    category: Priority order
    fluff: This mission is of the utmost importance, and cannot be entrusted to anyone else.
    text: When this Tactical Objective is generated, immediately generate a bonus Tactical Objective – this does not count towards the number of Active Tactical Objectives you currently have in play. Your Warlord is the only unit that can be used to achieve the bonus Tactical Objective – they must be the only unit used to control an objective marker, the unit that destroys the last model in an enemy unit, and so on. If you achieve this, you score both the number of victory points stated on the bonus Tactical Objective and an additional 3 victory points. If this Tactical Objective is discarded, so too is the bonus Tactical Objective.
    points:
      - 3
